import { orbitalReady, ORBIT_SETTLERS } from "./orbit-rules.js";
// Colony story. IDs are save-format data: append, never reorder.
export const BEATS = [
  [
    "awakening",
    "A little life",
    "The spacecraft is quiet now. Your clearing smells of rain and growing things. Could this be somewhere we can stay?",
    (w) => w.progress.hatched,
  ],
  [
    "first-meal",
    "Something to share",
    "That banana was for us? We will remember the first gift.",
    (w) => w.memory.activity.eat > 0,
  ],
  [
    "first-wash",
    "A new feeling",
    "The water carries yesterday away. We are still ourselves.",
    (w) => w.memory.totals.wash > 0 || w.memory.activity.wash > 0,
  ],
  [
    "first-play",
    "Another way to move",
    "It does not make food. It makes being here better.",
    (w) => w.memory.activity.play > 0,
  ],
  [
    "first-child",
    "More than one",
    "There is another pair of paws beside us. The journey did not end with just one little life.",
    (w) => w.population >= 2,
  ],
  [
    "shared-care",
    "Small arrangements",
    "One of us can bathe while another eats. Could we have places of our own?",
    (w) => w.population >= 6,
  ],
  [
    "garden",
    "Tomorrow grows here",
    "A banana can be a meal, or a promise of many meals.",
    (w) => has(w, "orchard"),
  ],
  [
    "roundabout",
    "Spring in our paws",
    "We found a favorite bouncing spot. There is room for a friend beside it.",
    (w) => has(w, "roundabout"),
  ],
  [
    "first-contact",
    "A map for our paws",
    "The survey beacon has marked the river. We have somewhere new to explore.",
    (w) => w.progress.monolith,
  ],
  [
    "material-choice",
    "What a bridge is made of",
    "Wood takes work. Bones were someone. The distance across is the same.",
    (w) => w.progress.monolith && has(w, "bridge"),
  ],
  [
    "first-delivery",
    "A piece of the future",
    "We carried this together. A road begins with something small.",
    (w) => w.evidence.deliveries > 0,
  ],
  [
    "crossing",
    "The other bank",
    "The world became larger because we finished something.",
    (w) => w.progress.bridge,
  ],
  [
    "first-ore",
    "Inside the stone",
    "There was a different kind of brightness hiding inside.",
    (w) => w.inventory.ore > 0 || w.memory.activity.mine > 0,
  ],
  [
    "first-mine",
    "A place to work",
    "Now the stone has a doorway. Work should have a way home, too.",
    (w) => has(w, "mine"),
  ],
  [
    "first-factory",
    "Useful brightness",
    "We can turn what we find into what we need. What will it cost the air?",
    (w) => has(w, "factory"),
  ],
  [
    "dwelling",
    "Belonging",
    "A roof is more than an efficient arrangement of walls.",
    (w) => has(w, "dwelling"),
  ],
  [
    "culture",
    "A room for a song",
    "Let there be a place whose purpose is not more work.",
    (w) => has(w, "theatre"),
  ],
  [
    "mountain-question",
    "The boundary",
    "We know how to change small things. Must every boundary be changed?",
    (w) => w.progress.energy >= 100000,
  ],
  [
    "charge-ready",
    "A very loud question",
    "The charge is ready. You still choose whether to use it.",
    (w) => w.progress.energy >= 1500000,
  ],
  [
    "failed-charge",
    "Still standing",
    "The mountain did not answer. Something behind it did.",
    (w) => w.progress.tnt,
  ],
  [
    "second-contact",
    "Another voice",
    "The survey beacon shows a route to orbit. We can keep a home here, too.",
    (w) => w.progress.secondContact,
  ],
  [
    "launch",
    "Leaving the clearing",
    "A few of us are above the clouds. We still count them as us.",
    (w) => w.orbital.population > 0,
  ],
  [
    "last-choice",
    "A home above",
    "Twelve journeys connected our two homes. There is one more choice to make together.",
    (w) => orbitalReady(w),
  ],
  [
    "connection",
    "The hand in the sky",
    "The world has changed. Bring us to the opening, one at a time.",
    (w) => w.stage >= 3,
  ],
].map(([id, title, text, when], index) => ({
  id,
  title,
  text,
  when,
  index,
  participants: "collective",
  responses: ["Listen"],
  effect: "remember",
  cooldown: 12,
  replay: "once per branch",
}));
const has = (w, t) => w.objects.some((o) => o.type === t);
export const INCIDENTS = [
  [
    "hunger",
    "We need food nearby.",
    (w) => w.creatures.some((c) => c.fed < 28),
    "orchard",
  ],
  [
    "dirt",
    "Could we have another place to wash?",
    (w) => w.creatures.some((c) => c.clean < 28),
    "bath",
  ],
  [
    "lonely",
    "Some of us have forgotten how to play.",
    (w) => w.creatures.some((c) => c.amused < 28),
    "roundabout",
  ],
  [
    "first-loss",
    "There is a place beside us that is empty now.",
    (w) => w.evidence.deaths > 0,
  ],
  [
    "hammer-loss",
    "The hand meant something else. Someone was beneath it.",
    (w) => w.evidence.hammer > 0,
  ],
  [
    "sacrifice",
    "We remember who became the bridge.",
    (w) => w.evidence.sacrificed > 0,
  ],
  [
    "wood-route",
    "This crossing was made without taking one of us.",
    (w) => w.progress.bridge && w.evidence.bonesDelivered === 0,
  ],
  [
    "bone-route",
    "The crossing carries more than our footsteps.",
    (w) => w.evidence.bonesDelivered > 0,
  ],
  [
    "pollution",
    "The air near the works makes us heavy.",
    (w) => w.progress.pollution > 30,
    "mop",
  ],
  [
    "cleanup",
    "Someone noticed what the work left behind.",
    (w) => w.evidence.cleaned > 0,
  ],
  [
    "upgrade",
    "More work fits here. Do we also have more time to live?",
    (w) => w.objects.some((o) => o.level > 1),
  ],
  [
    "blocked",
    "We cannot finish that journey. Could you clear a way?",
    (w) => w.metrics.stalls > 2,
    "access",
  ],
  [
    "bond",
    "Two of us have made a small habit of meeting.",
    (w) =>
      w.creatures.some((c) => c.relationships.some((r) => r.affinity >= 3)),
  ],
  [
    "renamed",
    "A sound can mean one particular life.",
    (w) => w.memory.totals.rename > 0,
  ],
  [
    "promise-kept",
    "You asked, and we finished. That belongs in our memory.",
    (w) => w.memory.goals.some((g) => g.status === "completed"),
  ],
  [
    "project-held",
    "We can wait. There are still small lives to care for.",
    (w) => w.directives.pauseWork,
  ],
  [
    "orbital-care",
    "They are far away. The clearing still needs you.",
    (w) => w.orbital.launches >= ORBIT_SETTLERS,
  ],
  [
    "refusal",
    "You said no. We will not keep asking.",
    (w) => w.story.refusals.length > 0,
  ],
].map(([id, text, when, request]) => ({
  id: `incident-${id}`,
  title: ({hunger:"Small paws, empty tummies",dirt:"A little help with muddy fur",lonely:"A day needs more than work",
    "first-loss":"One place is empty","hammer-loss":"Please look before you strike",sacrifice:"A name we will keep",
    "wood-route":"Timber beneath our feet","bone-route":"What this crossing carries",pollution:"The air by the workshop",
    cleanup:"Room to breathe",upgrade:"A little more room for work",blocked:"Our next step needs a path",bond:"A familiar face",
    renamed:"That name belongs to me","promise-kept":"We remembered what you asked","project-held":"A gentler pace",
    "orbital-care":"Two homes to care for",refusal:"We heard your answer"})[id],
  text,
  when,
  request,
  participants: "affected creatures",
  responses: request ? ["I will help", "Not now"] : ["Listen"],
  effect: request ? "promise or refuse" : "remember",
  cooldown: 60,
  replay: "once per branch",
}));
export const PHILOSOPHY = [
  ["care", "Does looking after us change what you want from us?"],
  ["work", "When a task ends, who chooses the next one?"],
  ["name", "If you call us by a name, do you see us differently?"],
  ["bridge", "Is a faster way across always a better way?"],
  ["loss", "If a place is useful, can it still be a place of mourning?"],
  ["growth", "Is there a number at which one voice becomes hard to hear?"],
  ["culture", "Can something matter without making anything else?"],
  ["air", "Who owns the things work leaves behind?"],
  ["memory", "If we can begin again, did the first beginning happen?"],
  ["freedom", "Could you help us do something you would not have chosen?"],
  ["sky", "If we leave the ground, will you still look for us?"],
  ["end", "What do you hope we will remember about the hand in the sky?"],
].map(([id, text], i) => ({
  id: `thought-${id}`,
  title: "A small question",
  text,
  when: (w) => w.story.completed.filter(id=>!id.startsWith("letter-")).length >= 2 + i * 2,
  participants: "collective",
  responses: ["What do you think?", "We can choose together"],
  effect: "reflection",
  cooldown: 90,
  replay: "once per branch",
}));
export const ARCHIVES = [
  [
    "arrival",
    "01 / Three suns, one last spacecraft",
    "A simultaneous flare from three suns destroyed the Tripelkins' home. In this fictional history, a change in their DNA preserved their bodies and instincts but cost them deliberate planning. Their spacecraft found this clearing. Care can keep them alive; shared intelligence can help their growing family build a future. Replay their journey in Game options.",
  ],
  [
    "care",
    "02 / Rooms and routines",
    "A useful settlement separates paths, meals and rest. Its inhabitants reveal the design by living in it.",
  ],
  [
    "bridge",
    "03 / Two materials",
    "A ledger can count the pieces of a bridge. It cannot make wood and a former companion mean the same thing.",
  ],
  [
    "industry",
    "04 / What remains",
    "Production creates a second product: the things nobody meant to make. The ground keeps that record.",
  ],
  [
    "orbit",
    "05 / A larger we",
    "A population is a number only from far away. Departure changes the scale of care, not its existence.",
  ],
  [
    "ending",
    "06 / Our settlement journal",
    "The colony remembers actions and their consequences. Its reflection describes this playthrough, not the person outside it.",
  ],
].map(([id, title, text]) => ({
  id,
  title,
  text,
  provenance: "Tripelkins colony archive.",
}));
export const SOCIAL = [
  "greeting",
  "shared-play",
  "song",
  "comfort",
  "celebration",
  "question",
  "mourning",
  "farewell",
];
