// Instrument the native consumer, execute indexed workflows, then ingest LLVM's
// own counts. Identical profile/selectors share an execution and LLVM snapshot;
// plan counts describe that suite, while the summary counts each execution once.
// Parity results are never substituted for code coverage.
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,existsSync} from 'node:fs';
import {join,relative} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync,execFileSync} from 'node:child_process';
import {ROOT} from './inventory.mjs';import {loadManifest,loadInputs} from './schema.mjs';import {runIdentity,ActualDate,fileDigest,digest,targetSourceFingerprint} from './identity.mjs';
const {manifest,registry}=loadManifest(join(ROOT,'tests/fixtures/manifest.json')),inputs=loadInputs(join(ROOT,'tests/fixtures/manifest.json'),manifest,registry),identity=runIdentity(manifest,[...inputs.coverage,...inputs.parity],'coverage',['rust-native']);
const declarations=inputs.coverage.flatMap(f=>f.input.plans),output=join(ROOT,'artifacts/migration'),scratch=mkdtempSync(join(tmpdir(),'tripelkins-native-coverage-'));mkdirSync(output,{recursive:true});
const infrastructure_errors=[],plans=[];let collector={name:'LLVM source-based coverage',version:'unavailable',snapshot_id:null,artifact_ingested:false};
function run(argv,options={}){const result=spawnSync(argv[0],argv.slice(1),{cwd:ROOT,encoding:'utf8',timeout:900000,maxBuffer:64*1024*1024,...options});if(result.error||result.status!==0)throw Error(`${argv.join(' ')}: ${result.error?.message||result.stderr||result.stdout}`.slice(0,4000));return result;}
try{
 const sysroot=execFileSync('rustc',['--print','sysroot'],{cwd:ROOT,encoding:'utf8'}).trim(),host=execFileSync('rustc',['-vV'],{cwd:ROOT,encoding:'utf8'}).match(/^host: (.+)$/m)[1],bin=join(sysroot,'lib/rustlib',host,'bin'),profdata=join(bin,'llvm-profdata'),cov=join(bin,'llvm-cov');
 if(!existsSync(profdata)||!existsSync(cov))throw Error('llvm-tools component is not installed for the active Rust toolchain.');collector.version=run([cov,'--version']).stdout.trim();
 const targetDir=join(scratch,'target'),env={...process.env,RUSTC_WRAPPER:'',RUSTFLAGS:'-C instrument-coverage',CARGO_TARGET_DIR:targetDir};
 const sourcePaths=[...readdirSync(join(ROOT,'engine/src')).filter(p=>p.endsWith('.rs')).map(p=>join(ROOT,'engine/src',p)),...readdirSync(join(ROOT,'engine/data')).map(p=>join(ROOT,'engine/data',p)),...['engine/Cargo.toml','engine/Cargo.lock','rust-toolchain.toml'].map(p=>join(ROOT,p))].filter(existsSync).sort();const sourceHash=()=>digest(sourcePaths.map(p=>relative(ROOT,p)+':'+fileDigest(p)).join('\n'));const before=sourceHash(),consumerBefore=targetSourceFingerprint();
 console.log('Building instrumented native engine.');run(['cargo','build','--manifest-path','engine/Cargo.toml','--release','--offline'],{env});const binary=join(targetDir,'release/tripelkins-engine');
 const snapshotEntries=[],collections=new Map();
 for(const plan of declarations){const collectionKey=JSON.stringify([plan.target_profile,plan.selectors]);let collected=collections.get(collectionKey);if(!collected){const directory=join(scratch,plan.plan_id);mkdirSync(directory,{recursive:true});const raw=join(directory,'%p-%m.profraw'),selected=new Set(plan.selectors.parity_case_ids),casePath=join(directory,'cases.json');writeFileSync(casePath,JSON.stringify([...selected]));
 const testEnv={...process.env,LLVM_PROFILE_FILE:raw,MIGRATION_NATIVE_ARGV:JSON.stringify([binary]),MIGRATION_PROFILES:'rust-native',MIGRATION_CASE_IDS_FILE:casePath,MIGRATION_RESULT_PATH:join(directory,'parity.json')};
 console.log(`Collecting ${plan.plan_id}: ${selected.size} public workflows.`);let passed=0,failed=0,status='completed';try{run(['node','scripts/migration/contracts/parity.mjs'],{env:testEnv});}catch(error){status='failed';if(!existsSync(join(directory,'parity.json')))throw error;}
 const result=JSON.parse(readFileSync(join(directory,'parity.json')));passed=result.summary.passed;failed=result.summary.failed;if(result.infrastructure_errors.length)throw Error('Instrumented parity infrastructure failed: '+result.infrastructure_errors[0].message);
 for(const id of plan.selectors.command_ids){const command=registry.commands.get(id);try{const executed=run(command.argv,{env:{...testEnv,TRIPELKINS_ENGINE_ARGV:JSON.stringify([binary])},cwd:join(ROOT,command.cwd)});writeFileSync(join(output,`coverage-${plan.plan_id}-${id}.log`),executed.stdout+'\n'+executed.stderr);const text=executed.stdout.trim(),at=text.lastIndexOf('\n{');try{const counts=JSON.parse(text.slice(at<0?0:at+1));passed+=counts.passed||0;failed+=counts.failed||0;if(counts.failed)status='failed';}catch{}}catch(e){writeFileSync(join(output,`coverage-${plan.plan_id}-${id}.log`),String(e));failed++;status='failed';}}
 const profiles=readdirSync(directory).filter(f=>f.endsWith('.profraw')).map(f=>join(directory,f));if(!profiles.length)throw Error('Instrumented executable produced no coverage profiles.');const merged=join(directory,'merged.profdata');const profileList=join(directory,'profiles.txt');writeFileSync(profileList,profiles.join('\n')+'\n');run([profdata,'merge','-sparse','--input-files='+profileList,'-o',merged]);const exported=run([cov,'export',binary,`-instr-profile=${merged}`]).stdout;const rawPath=join(output,`coverage-${plan.plan_id}.llvm.json`);writeFileSync(rawPath,exported);const data=JSON.parse(exported);if(data.type!=='llvm.coverage.json.export')throw Error('Unexpected LLVM export schema');snapshotEntries.push(fileDigest(rawPath));
 collected={files:data.data.flatMap(d=>d.files),passed,failed,status};collections.set(collectionKey,collected);}
 const {files,passed,failed,status}=collected;const components=plan.component_ids.map(id=>{const component=registry.components.get(id),selectedFiles=files.filter(f=>component.paths.includes(relative(ROOT,f.filename))),dimensions=['function','line','branch','region'],key={function:'functions',line:'lines',branch:'branches',region:'regions'};return {component_id:id,files:selectedFiles.map(f=>({path:relative(ROOT,f.filename),dimensions:dimensions.map(d=>{const s=f.summary[key[d]]||{count:0,covered:0};return {dimension:d,covered:s.covered,total:s.count,uncovered:d==='line'||d==='region'?f.segments.filter(v=>v[3]&&v[2]===0&&!v[5]).map(v=>`${relative(ROOT,f.filename)}:${v[0]}:${v[1]}`):[]};})})),thresholds:component.thresholds.map(t=>{const total=selectedFiles.reduce((n,f)=>n+(f.summary[key[t.dimension]]?.count||0),0),covered=selectedFiles.reduce((n,f)=>n+(f.summary[key[t.dimension]]?.covered||0),0);return {...t,covered,total,outcome:!total?'not_proven':100*covered>=t.minimum_percent*total?'pass':'fail'};})};});
 plans.push({plan_id:plan.plan_id,target_profile:plan.target_profile,requirements:plan.covers,selected:plan.selectors,execution:{status,tests_passed:passed,tests_failed:failed},components});
 }
 if(sourceHash()!==before||targetSourceFingerprint()!==consumerBefore)throw Error('Rust source changed during coverage collection; rerun against a stable source snapshot.');collector.snapshot_id='sha256:'+digest(snapshotEntries.join('\n'));collector.artifact_ingested=true;
}catch(error){infrastructure_errors.push({scope:'collector',id:null,kind:'coverage_collection_failed',message:error.message.slice(0,4000)});}
for(const plan of declarations)if(!plans.some(p=>p.plan_id===plan.plan_id))plans.push({plan_id:plan.plan_id,target_profile:plan.target_profile,requirements:plan.covers,selected:plan.selectors,execution:{status:'not_run',tests_passed:0,tests_failed:0},components:[]});
identity.finished_at=new ActualDate().toISOString();const result={schema:'migration-parity/coverage-result@1',identity,status:infrastructure_errors.length?'infrastructure_failed':collector.artifact_ingested?'completed':'not_ingested',collector,summary:{plans_selected:plans.length,plans_executed:plans.filter(p=>p.execution.status!=='not_run').length,plans_not_run:plans.filter(p=>p.execution.status==='not_run').length,tests_passed:[...new Map(plans.map(p=>[JSON.stringify([p.target_profile,p.selected]),p.execution])).values()].reduce((n,e)=>n+e.tests_passed,0),tests_failed:[...new Map(plans.map(p=>[JSON.stringify([p.target_profile,p.selected]),p.execution])).values()].reduce((n,e)=>n+e.tests_failed,0)},plans,infrastructure_errors};writeFileSync(join(output,'coverage.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,...result.summary,thresholds:plans.flatMap(p=>p.components.flatMap(c=>c.thresholds)).reduce((counts,t)=>({...counts,[t.outcome]:(counts[t.outcome]||0)+1}),{})}));if(infrastructure_errors.length||result.summary.tests_failed||plans.some(p=>p.execution.status!=='completed'||p.components.some(c=>c.thresholds.some(t=>t.outcome!=='pass'))))process.exitCode=1;
