import {readFileSync,existsSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {join,resolve} from 'node:path';
import {ROOT,SOURCE_REVISION} from './inventory.mjs';
export const ActualDate=Date;
export const digest=data=>createHash('sha256').update(data).digest('hex');
export const fileDigest=path=>digest(readFileSync(path));
export const manifestPath='tests/fixtures/manifest.json';
export function oracleIdentity(){return {oracle_id:'javascript-reference',name:'Tripelkins JavaScript simulation',version:SOURCE_REVISION,runtime:`Node.js ${process.version}`};}
let featureCache;
export function targetFeatures(){if(!featureCache){const metadata=JSON.parse(execFileSync('cargo',['metadata','--manifest-path','engine/Cargo.toml','--format-version','1','--offline'],{cwd:ROOT,encoding:'utf8',env:{...process.env,RUSTC_WRAPPER:''}}));const names=new Map(metadata.packages.map(p=>[p.id,p.name+'@'+p.version]));featureCache=metadata.resolve.nodes.flatMap(n=>n.features.map(f=>names.get(n.id)+'/'+f)).sort();}return [...featureCache];}
export function targetSourceFingerprint(){const files=[];for(const base of ['engine/src','engine/data','engine/tests','scripts/migration','tests/deprecated/migration-diagnostics']){const scan=p=>{for(const entry of readdirSync(join(ROOT,p),{withFileTypes:true})){const path=p+'/'+entry.name;if(entry.isDirectory())scan(path);else if(/\.(?:rs|mjs|json)$/.test(path))files.push(path);}};scan(base);}files.push('engine/Cargo.toml','engine/Cargo.lock','rust-toolchain.toml');return digest(files.sort().map(p=>p+':'+fileDigest(join(ROOT,p))).join('\n'));}
export function targetIdentity(profile){const artifact=profile==='rust-wasm'?'engine/pkg/tripelkins_engine_bg.wasm':'engine/target/release/tripelkins-engine';const status=execFileSync('git',['status','--porcelain'],{cwd:ROOT,encoding:'utf8'});return {target_profile:profile,target_id:'rust-engine',revision:existsSync(join(ROOT,artifact))?`sha256:${fileDigest(join(ROOT,artifact))};consumer:${targetSourceFingerprint()}`:'missing-artifact',dirty:!!status.trim(),runtime:execFileSync('rustc',['--version'],{cwd:ROOT,encoding:'utf8'}).trim(),backend:profile==='rust-wasm'?'wasm32-unknown-unknown':'native',features:targetFeatures()};}
export function runIdentity(manifest,inputs,lane,profiles){const start=new ActualDate().toISOString();return {run_id:`${lane}-${start.replace(/[^0-9]/g,'')}-${process.pid}`,started_at:start,finished_at:start,manifest:{path:manifestPath,schema:manifest.schema,sha256:fileDigest(join(ROOT,manifestPath))},inputs:inputs.map(({path,input})=>({path:'tests/fixtures/'+path,schema:input.schema,sha256:fileDigest(join(ROOT,'tests/fixtures',path))})),assets:inputs.flatMap(({path,input})=>(input.cases||input.workloads||[]).flatMap(item=>(item.assets||item.input?.assets||[]).map(a=>({input_path:'tests/fixtures/'+path,item_id:item.case_id||item.workload_id,asset_id:a.id,kind:a.kind,locator:a.path||a.name||null,sha256:a.sha256||null})))),oracles:[oracleIdentity()],targets:profiles.map(targetIdentity),command:(()=>{const c=manifest.commands.find(c=>c.id===`migration-${lane}`);return {command_id:c.id,argv:c.argv,cwd:c.cwd,timeout_seconds:c.timeout_seconds};})()};}
if(process.argv[1]&&resolve(process.argv[1])===new URL(import.meta.url).pathname)console.log(JSON.stringify(process.argv[2]==='oracle'?oracleIdentity():['rust-native','rust-wasm'].map(targetIdentity),null,2));
