import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {ROOT} from './inventory.mjs';
import {loadManifest,loadInputs} from './schema.mjs';
import {runIdentity,ActualDate} from './identity.mjs';
import {runSource,runTarget,compare} from './runner.mjs';
const {manifest,registry}=loadManifest(join(ROOT,'tests/fixtures/manifest.json')),inputs=loadInputs(join(ROOT,'tests/fixtures/manifest.json'),manifest,registry);
const selectedIds=process.env.MIGRATION_CASE_IDS_FILE?new Set(JSON.parse(readFileSync(process.env.MIGRATION_CASE_IDS_FILE))):null;
const profiles=process.env.MIGRATION_PROFILES?.split(',')||['rust-native','rust-wasm'];const selected=inputs.parity.flatMap(f=>f.input.cases).filter(c=>(!selectedIds||selectedIds.has(c.case_id))&&(!process.env.MIGRATION_CASE_FILTER||c.case_id.includes(process.env.MIGRATION_CASE_FILTER)));
const identity=runIdentity(manifest,inputs.parity,'parity',profiles),comparisons=[],infrastructure_errors=[];
for(const c of selected){let source;try{source=await runSource(c,registry);}catch(e){infrastructure_errors.push({scope:'oracle',id:c.case_id,kind:'oracle_failure',message:e.message.slice(0,1000)});}for(const profile of profiles.filter(p=>c.target_profiles.includes(p))){let target,diffs=[],outcome='not_run';try{if(!source)throw Error('Oracle not available');target=await runTarget(c,registry,profile);diffs=compare(source,target,c,registry);outcome=diffs.length?'fail':'pass';}catch(e){infrastructure_errors.push({scope:'target',id:c.case_id+'@'+profile,kind:'adapter_failure',message:e.message.slice(0,1000)});}const skipped={case_id:c.case_id,status:'not_run',observations:c.observations.map(step_id=>({step_id,status:'not_run',reason:'Adapter infrastructure failure'}))};comparisons.push({case_id:c.case_id,target_profile:profile,requirements:c.covers,source:source||skipped,target:target||skipped,outcome,diffs});if(outcome==='fail')console.error(`FAIL ${c.case_id} ${profile}: ${diffs[0].path}`);}}
identity.finished_at=new ActualDate().toISOString();const result={schema:'migration-parity/parity-result@1',identity,status:infrastructure_errors.length?'infrastructure_failed':'completed',summary:{selected:comparisons.length,executed:comparisons.filter(c=>c.outcome!=='not_run').length,passed:comparisons.filter(c=>c.outcome==='pass').length,failed:comparisons.filter(c=>c.outcome==='fail').length,not_run:comparisons.filter(c=>c.outcome==='not_run').length,infrastructure_errors:infrastructure_errors.length},comparisons,infrastructure_errors};mkdirSync(join(ROOT,'artifacts/migration'),{recursive:true});writeFileSync(process.env.MIGRATION_RESULT_PATH||join(ROOT,'artifacts/migration/parity.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));if(result.summary.failed||infrastructure_errors.length)process.exitCode=1;
