// Both sides receive the same authored workflow, never each other's results.
import {performance as measurementClock} from 'node:perf_hooks';
import {createInterface} from 'node:readline';
import {spawn} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {ROOT,oracleDirectory} from './inventory.mjs';
Object.defineProperty(globalThis,'crypto',{value:{getRandomValues(a){a.fill(18492);return a;},randomUUID(){return '00000000-0000-4000-8000-000000000001';}}});
Object.defineProperty(globalThis,'performance',{value:{now:()=>0}});
const fixed=Date;globalThis.Date=class extends fixed{constructor(...a){super(...(a.length?a:['2000-01-01T00:00:00.000Z']));}static now(){return 946684800000;}};
export const wire=value=>JSON.parse(JSON.stringify(value??null,(_k,v)=>v instanceof Map?[...v.entries()]:v instanceof Set?[...v]:ArrayBuffer.isView(v)?[...v]:v));
const modules=new Map();async function sourceModule(surface){if(!modules.has(surface))modules.set(surface,await import(pathToFileURL(join(oracleDirectory(),`src/game/${surface.slice(5)}.js`))));return modules.get(surface);}
async function assetsFor(item){const assets=new Map();for(const asset of item.assets){if(asset.kind==='builtin'){if(asset.name.startsWith('runtime.callback:')){assets.set(asset.id,JSON.parse(asset.name.slice(17)));continue;}if(asset.name.startsWith('runtime.')){assets.set(asset.id,asset.name);continue;}const last=asset.name.lastIndexOf('.');assets.set(asset.id,(await sourceModule(asset.name.slice(0,last)))[asset.name.slice(last+1)]);}else if(asset.kind==='inline'){const data=asset.encoding==='base64'?Buffer.from(asset.data,'base64').toString():asset.data;assets.set(asset.id,asset.media_type==='application/json'?JSON.parse(data):data);}else if(asset.kind==='ref')assets.set(asset.id,JSON.parse(readFileSync(join(ROOT,'tests/fixtures/assets',asset.path))));else throw Error(`Unsupported executable asset ${asset.kind}`);}return assets;}
function resolve(d,bindings,assets){return d.kind==='literal'?structuredClone(d.value):d.kind==='binding'?bindings.get(d.step_id):assets.get(d.asset_id);}
function linked(v,w){if(!w||v==null)return v;const id=typeof v==='string'?v:v?.id;return id?[...(w.creatures||[]),...(w.objects||[])].find(o=>o.id===id)||v:v;}
function prepare(step,bindings,assets){const a=Object.fromEntries(Object.entries(step.arguments).map(([k,d])=>[k,resolve(d,bindings,assets)]));const w=a.w||a.world;for(const key of ['c','o','factory','parent'])if(key in a&&w)a[key]=linked(a[key],w);if(a.victims&&w)a.victims=a.victims.map(v=>linked(v,w));return {a,w};}
function errorResult(error){return {class:error.name||'Error',kind:'public_error',message:String(error.message||error),stage:'call',code:null};}
function serialized(a){return Object.fromEntries(Object.entries(a).filter(([,v])=>typeof v!=='function'));}
export async function runSourceInProcess(item,registry,measurements=null){const assets=await assetsFor(item),bindings=new Map(),observations=[];for(const step of item.steps){const op=registry.operations.get(`${step.surface}.${step.operation}`);const {a,w}=prepare(step,bindings,assets);try{const mod=await sourceModule(step.surface);const args=op.source.parameters.map(p=>a[p.id]);if(a.operation?.surface){const d=a.operation,callback=await sourceModule(d.surface),parameters=registry.operations.get(`${d.surface}.${d.operation}`).source.parameters;const at=op.source.parameters.findIndex(p=>p.id==='operation');args[at]=()=>callback[d.operation](...parameters.map(p=>p.id==='w'?w:d.arguments[p.id]));}if(step.surface==='game.navigation-grid'&&op.kind==='function'){const i=op.source.parameters.findIndex(p=>p.id==='tiles');args[i]=new Map(args[i]);args[i+1]=Uint8Array.from(args[i+1]);}const started=measurementClock.now();let result=op.kind==='constant'?mod[step.operation]:await mod[step.operation](...args);if(measurements)measurements.push({step_id:step.step_id,milliseconds:measurementClock.now()-started});let mutations;const functionKey=`${step.surface}.${step.operation}`;if(functionKey==='game.navigation-grid.copyOccupancy'){mutations={tiles:[...args[1].entries()].map(([k,v])=>[k,[...v]]),grid:[...args[2]]};}else if(functionKey==='game.memory.compactEvents'){mutations={memory:a.memory};}else if(functionKey==='game.identity.encounter'){mutations={c:a.c};}bindings.set(step.step_id,result);if(item.observations.includes(step.step_id))observations.push({step_id:step.step_id,status:'ok',value:wire({result:result??null,world:w||null,...(mutations?{mutations}:{})})});}catch(error){if(item.observations.includes(step.step_id))observations.push({step_id:step.step_id,status:'error',error:errorResult(error)});}}
return {case_id:item.case_id,status:'completed',observations};}
// Match the target's fresh process boundary. Reference module caches and JIT
// warm-up from a previous workflow must not leak into the next observation.
export async function runSource(item,registry,measurements=null){
 const child=spawn(process.execPath,['scripts/migration/contracts/source-cli.mjs'],{cwd:ROOT,stdio:['pipe','pipe','pipe']}),lines=[],errors=[];
 child.stdout.on('data',chunk=>lines.push(chunk));child.stderr.on('data',chunk=>errors.push(chunk));
 const timer=setTimeout(()=>child.kill('SIGKILL'),120000);
 try{
  const closed=new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',(code,signal)=>code===0?resolve():reject(Error(`Reference infrastructure failure: ${signal||code}: ${Buffer.concat(errors).toString().slice(0,1000)}`)));});
  child.stdin.end(JSON.stringify(item));await closed;
  const response=JSON.parse(Buffer.concat(lines).toString());
  if(measurements)measurements.push(...response.measurements);
  return response.result;
 }finally{clearTimeout(timer);}
}
export async function runTarget(item,registry,profile,measurements=null){
 const bindings=new Map(),assets=new Map(item.assets.map(a=>[a.id,a.kind==='builtin'?(a.name.startsWith('runtime.callback:')?JSON.parse(a.name.slice(17)):{builtin:a.name}):a.kind==='inline'?JSON.parse(a.data):JSON.parse(readFileSync(join(ROOT,'tests/fixtures/assets',a.path)))])),observations=[];
 const argv=profile==='rust-wasm'?['node','scripts/migration/wasm-cli.mjs']:(process.env.MIGRATION_NATIVE_ARGV?JSON.parse(process.env.MIGRATION_NATIVE_ARGV):['engine/target/release/tripelkins-engine']);
 const child=spawn(argv[0],argv.slice(1),{cwd:ROOT,stdio:['pipe','pipe','pipe']}),pending=[];let failure=null,stderr='',loadedWorld=Symbol('unloaded');
 const closed=new Promise(resolve=>child.on('close',resolve));
 const timeout=setTimeout(()=>{failed(Error('Target workflow timed out after 120 seconds'));child.kill('SIGKILL');},120000);
 const failed=error=>{failure=error;while(pending.length)pending.shift().reject(error);};child.on('error',failed);child.stderr.on('data',s=>stderr+=String(s));child.on('exit',(code,signal)=>{if(code!==0)failed(Error(`Target infrastructure failure: ${signal||stderr||code}`));else if(pending.length)failed(Error('Target exited before responding'));});
 createInterface({input:child.stdout}).on('line',line=>{const waiter=pending.shift();if(!waiter){failed(Error('Extra target response'));return;}try{waiter.resolve(JSON.parse(line));}catch{waiter.reject(Error('Malformed target transport'));}});
 const request=(operation,input)=>{if(failure)return Promise.reject(failure);return new Promise((resolve,reject)=>{pending.push({resolve,reject});child.stdin.write(JSON.stringify({operation,input})+'\n');});};
 try{for(const step of item.steps){const {a,w}=prepare(step,bindings,assets),op=registry.operations.get(`${step.surface}.${step.operation}`);if(loadedWorld!==w){const loaded=await request('load',w||{});if(loaded.status!=='ok')throw Error('Target world load failed');const clock=await request('clock',{iso:'2000-01-01T00:00:00.000Z',monotonicMs:0});if(clock.status!=='ok')throw Error('Target clock setup failed');loadedWorld=w;}
 const arguments_=serialized(a);if(step.surface==='game.memory'&&step.operation==='beginCommand')arguments_.id='00000000-0000-4000-8000-000000000001';if(step.surface==='game.timeline'&&step.operation==='appendTimeline')arguments_.ids=['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000001'];delete arguments_.w;delete arguments_.world;
 const operation=op.kind==='constant'?'contract.constant':'contract.call',args={surface:step.surface,operation:step.operation,arguments:arguments_};const r=measurements?await request('__measure',{operation,input:args}):await request(operation,args);if(measurements&&r.status==='ok'){measurements.push({step_id:step.step_id,milliseconds:r.value.elapsedMs});r.value=r.value.value;}
 const snapshot=await request('snapshot',{});if(snapshot.status!=='ok')throw Error('Target snapshot failed');if(r.status==='error'&&/Unsupported engine|Unbound public|Unknown public/.test(r.message))throw Error(r.message);if(r.status==='ok'){bindings.set(step.step_id,r.value);if(w){for(const k of Object.keys(w))delete w[k];Object.assign(w,snapshot.value);}if(item.observations.includes(step.step_id))observations.push({step_id:step.step_id,status:'ok',value:wire(targetObservation(step,r.value,w))});}else if(r.status==='error'){if(item.observations.includes(step.step_id))observations.push({step_id:step.step_id,status:'error',error:errorResult({name:'Error',message:r.message})});}else throw Error('Malformed target status');}
 }finally{child.stdin.end();await closed;clearTimeout(timeout);}if(failure)throw failure;return {case_id:item.case_id,status:'completed',observations};
}
export function compare(source,target,item,registry){const diffs=[];const difference=(step_id,path,s,t,message)=>{if(diffs.length<20)diffs.push({step_id,path,kind:'value_mismatch',source:s??null,target:t??null,message});};const ss=source.observations.map(x=>x.step_id).sort(),ts=target.observations.map(x=>x.step_id).sort();if(JSON.stringify(ss)!==JSON.stringify(ts))throw Error('Observed step ID-set disagreement');for(const so of source.observations){const to=target.observations.find(t=>t.step_id===so.step_id);if(so.status!==to.status){difference(so.step_id,'status',so.status,to.status,'Public status differs');continue;}if(so.status==='error'){for(const key of ['class','kind','message','stage','code'])if(so.error[key]!==to.error[key])difference(so.step_id,'error.'+key,so.error[key],to.error[key],'Public error differs');continue;}const step=item.steps.find(s=>s.step_id===so.step_id);const rules=registry.operations.get(`${step.surface}.${step.operation}`).source.result.observations[0].comparison;function walk(a,b,path){if(typeof a==='number'&&typeof b==='number'){if(Math.abs(a-b)>rules.absolute_tolerance+rules.relative_tolerance*Math.max(Math.abs(a),Math.abs(b)))difference(so.step_id,path,a,b,'Numeric tolerance exceeded');return;}if(a&&b&&typeof a==='object'&&typeof b==='object'){if(Array.isArray(a)!==Array.isArray(b)){difference(so.step_id,path,a,b,'Container type differs');return;}const aa=Object.keys(a).sort(),bb=Object.keys(b).sort();if(JSON.stringify(aa)!==JSON.stringify(bb))difference(so.step_id,path+'.keys',aa,bb,'Key set differs');for(const k of aa)if(k in b)walk(a[k],b[k],path+'.'+k);return;}if(a!==b)difference(so.step_id,path,a,b,'Exact value differs');}walk(so.value,to.value,'value');}return diffs;}

function targetObservation(step,value,w){const key=`${step.surface}.${step.operation}`;if(key==='game.memory.compactEvents')return {result:null,world:w||null,mutations:{memory:value}};if(key==='game.identity.encounter')return {result:null,world:w||null,mutations:{c:value}};if(key==='game.navigation-grid.copyOccupancy')return {result:null,world:w||null,mutations:value};return {result:value,world:w||null};}
