// Fixed interfaces for migration declarations. Parameter names belong to the
// source API; literal input data is never recursively interpreted as metadata.
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve,relative,join} from 'node:path';
export const schemas={manifest:'migration-parity/manifest@2',parity:'migration-parity/parity-input@1',coverage:'migration-parity/coverage-input@1',benchmark:'migration-parity/benchmark-input@1'};
const values=new Set('null boolean integer number string bytes path enum sequence mapping record image font stream handle any_json'.split(' '));
const dimensions=new Set('parameter parameter_combination input_family success_path error_path mode format protocol_variant abi_variant asset_family boundary backend runtime feature historical_divergence code_path performance documentation'.split(' '));
const metrics=new Set('latency throughput allocations peak_memory resident_memory artifact_size encoded_size startup_time cpu_time'.split(' '));
function fail(path,message){throw new Error(`${path}: ${message}`);}
export function exact(value,keys,path,optional=[]){if(!value||typeof value!=='object'||Array.isArray(value))fail(path,'expected object');const allowed=new Set([...keys,...optional]);for(const key of Object.keys(value))if(!allowed.has(key))fail(path,`unknown field ${key}`);for(const key of keys)if(!(key in value))fail(path,`missing field ${key}`);return value;}
function str(v,p){if(typeof v!=='string'||!v.length)fail(p,'expected non-empty string');return v;}
function arr(v,p){if(!Array.isArray(v))fail(p,'expected array');return v;}
function unique(v,p){arr(v,p);if(new Set(v).size!==v.length)fail(p,'duplicate entries');return v;}
function enumeration(v,choices,p){if(!choices.includes(v))fail(p,`unsupported value ${v}`);return v;}
function id(v,p){str(v,p);if(!/^[A-Za-z_][A-Za-z0-9_.:-]*$/.test(v))fail(p,'invalid public identifier');return v;}
function positive(v,p,allowZero=false){if(typeof v!=='number'||!Number.isFinite(v)||(allowZero?v<0:v<=0))fail(p,'expected positive finite number');}
function ref(value,registry,p){if(!registry.has(value))fail(p,`unknown reference ${value}`);}
export function safePath(value,p){str(value,p);if(value.startsWith('/')||value.split(/[\\/]/).includes('..'))fail(p,'path escapes repository');return value;}
function comparison(v,p){str(v?.kind,p);const common={exact:['kind'],ordered:['kind'],unordered:['kind'],bytes:['kind'],numeric:['kind','absolute_tolerance','relative_tolerance','nan_policy'],text:['kind','transforms','reason'],image:['kind','pixel_mode','maximum_channel_delta','metadata_mode','reason'],filesystem:['kind','path_mode','ordering','content_mode']};if(!common[v.kind])fail(p,'unsupported comparison');exact(v,common[v.kind],p);if(v.kind==='numeric'){positive(v.absolute_tolerance,p,true);positive(v.relative_tolerance,p,true);enumeration(v.nan_policy,['forbidden','equal','unequal'],p);}if(v.kind==='text'){transforms(v.transforms,p);str(v.reason,p);}if(v.kind==='image'){enumeration(v.pixel_mode,['exact','bounded_delta'],p);positive(v.maximum_channel_delta,p,true);enumeration(v.metadata_mode,['exact','declared_only','ignored'],p);if(v.pixel_mode==='exact'&&v.maximum_channel_delta!==0)fail(p,'exact images require zero delta');if(v.pixel_mode!=='exact'||v.metadata_mode!=='exact')str(v.reason,p);}if(v.kind==='filesystem'){assert.equal(v.path_mode,'relative');assert.equal(v.ordering,'sorted');assert.equal(v.content_mode,'exact');}}
function transforms(a,p){for(const v of unique(a,p))enumeration(v,['normalize_newlines','normalize_path_separators','strip_runtime_addresses','unicode_nfc'],p);}
function errorContract(v,p){exact(v,['fields','message'],p);for(const k of unique(v.fields,p))enumeration(k,['class','kind','message','stage','code'],p);exact(v.message,['mode','transforms','reason'],p);enumeration(v.message.mode,['exact','normalized','ignored'],p);transforms(v.message.transforms,p);if(v.message.mode==='exact'){if(v.message.transforms.length||v.message.reason!==null)fail(p,'exact errors cannot normalize');}else str(v.message.reason,p);}
function omission(v,p){str(v?.kind,p);if(v.kind==='required')exact(v,['kind'],p);else if(v.kind==='literal')exact(v,['kind','value'],p);else if(v.kind==='sentinel'){exact(v,['kind','name','semantics'],p);str(v.name,p);str(v.semantics,p);}else fail(p,'unsupported omission');}
function budget(v,p,registries){exact(v,['kind','metric','statistic','operator','value','unit','baseline_subject'],p);enumeration(v.kind,['absolute','relative'],p);if(!metrics.has(v.metric))fail(p,'unsupported metric');enumeration(v.statistic,['min','median','mean','p95','p99','max','total','weighted_mean'],p);enumeration(v.operator,['less_than_or_equal','greater_than_or_equal'],p);positive(v.value,p,true);str(v.unit,p);if(v.kind==='absolute'&&v.baseline_subject!==null)fail(p,'absolute budget has baseline');if(v.kind==='relative'&&!registries.profiles.has(v.baseline_subject)&&!registries.oracles.has(v.baseline_subject))fail(p,'unknown budget baseline');}
function command(v,p){exact(v,['id','argv','cwd','timeout_seconds'],p);id(v.id,p);if(!arr(v.argv,p).length)fail(p,'empty command');v.argv.forEach(x=>str(x,p));safePath(v.cwd,p);positive(v.timeout_seconds,p);}
function keyed(items,p){const m=new Map();for(const item of arr(items,p)){id(item.id,p);if(m.has(item.id))fail(p,`duplicate ${item.id}`);m.set(item.id,item);}return m;}
export function validateManifest(m){
 exact(m,['schema','scope','oracles','targets','target_profiles','commands','interfaces','input_index','coverage_components','surfaces','documentation'],'manifest');assert.equal(m.schema,schemas.manifest);exact(m.scope,['id','mode','inventory'],'scope');id(m.scope.id,'scope');enumeration(m.scope.mode,['slice','full'],'scope');exact(m.scope.inventory,['authority','revision','command_id'],'inventory');str(m.scope.inventory.authority,'inventory');str(m.scope.inventory.revision,'inventory');
 const r={oracles:keyed(m.oracles,'oracles'),targets:keyed(m.targets,'targets'),profiles:keyed(m.target_profiles,'profiles'),commands:keyed(m.commands,'commands'),components:keyed(m.coverage_components,'components'),surfaces:keyed(m.surfaces,'surfaces'),operations:new Map(),requirements:new Map()};
 for(const c of m.commands)command(c,'command');ref(m.scope.inventory.command_id,r.commands,'inventory');
 for(const o of m.oracles){exact(o,['id','name','version','runtime','identity_command_id','contract','components'],'oracle');for(const k of ['name','version','runtime','contract'])str(o[k],`oracle.${k}`);ref(o.identity_command_id,r.commands,'oracle');for(const c of arr(o.components,'components')){exact(c,['id','name','version'],'component');for(const key of ['id','name','version'])str(c[key],key);}}
 for(const t of m.targets){exact(t,['id','name','runtime','identity_command_id','contract'],'target');for(const k of ['name','runtime','contract'])str(t[k],k);ref(t.identity_command_id,r.commands,'target');}
 for(const p of m.target_profiles){exact(p,['id','target_id','backend','features'],'profile');ref(p.target_id,r.targets,'profile');str(p.backend,'profile');unique(p.features,'features');}
 exact(m.interfaces,['parity','coverage','benchmark','aggregation'],'interfaces');for(const lane of ['parity','coverage','benchmark']){const i=m.interfaces[lane];exact(i,['input_schema','result_schema','command_id'],lane);assert.equal(i.input_schema,schemas[lane]);assert.equal(i.result_schema,`migration-parity/${lane}-result@1`);ref(i.command_id,r.commands,lane);}const ag=m.interfaces.aggregation;exact(ag,['input_schemas','result_schema','command_id'],'aggregation');assert.deepEqual([...ag.input_schemas].sort(),['benchmark','coverage','parity'].map(l=>`migration-parity/${l}-result@1`));assert.equal(ag.result_schema,'migration-parity/status-report@1');ref(ag.command_id,r.commands,'aggregation');
 exact(m.input_index,['parity','coverage','benchmark'],'input_index');for(const lane of ['parity','coverage','benchmark'])for(const p of unique(m.input_index[lane],lane)){safePath(p,lane);if(!p.startsWith(`inputs/${lane}/`))fail(lane,'input outside lane root');}
 for(const c of m.coverage_components){exact(c,['id','target_profile','paths','dimensions','thresholds'],'component');ref(c.target_profile,r.profiles,'component');if(!arr(c.paths,'paths').length)fail('component','empty paths');c.paths.forEach(p=>safePath(p,'component'));for(const d of unique(c.dimensions,'dimensions'))enumeration(d,['function','line','branch','region'],'dimension');for(const t of arr(c.thresholds,'thresholds')){exact(t,['dimension','minimum_percent'],'threshold');enumeration(t.dimension,c.dimensions,'threshold');positive(t.minimum_percent,'threshold',true);if(t.minimum_percent>100)fail('threshold','percentage above 100');}}
 for(const s of m.surfaces){exact(s,['id','kind','source_path','storage_slug','operations'],'surface');enumeration(s.kind,['namespace','type','format','abi','cli','protocol','service'],'surface');str(s.source_path,'surface');if(!/^[a-z0-9][a-z0-9-]*$/.test(s.storage_slug))fail('surface','invalid storage slug');for(const o of arr(s.operations,'operations')){
  exact(o,['id','kind','classification','lifecycle','source','targets','requirements','parity','coverage','benchmark'],`${s.id}.${o.id}`);id(o.id,'operation');const key=`${s.id}.${o.id}`;if(r.operations.has(key))fail(key,'duplicate operation');r.operations.set(key,o);enumeration(o.kind,'function method constructor property_get property_set command abi_function protocol_operation format_operation constant type enum enum_variant flag macro record tag error namespace'.split(' '),key);enumeration(o.classification,['endpoint','non_endpoint'],key);
  if(o.lifecycle.status==='current')exact(o.lifecycle,['status'],key);else {exact(o.lifecycle,['status','authority','replacement'],key);assert.equal(o.lifecycle.status,'deprecated');str(o.lifecycle.authority,key);}
  const src=o.source;exact(src,['oracle_id','path','signature','parameters','result'],key);ref(src.oracle_id,r.oracles,key);str(src.path,key);str(src.signature,key);const parameters=keyed(src.parameters,key);for(const p of parameters.values()){exact(p,['id','style','value_types','omission'],key);enumeration(p.style,'receiver positional positional_or_keyword keyword variadic_positional variadic_keyword input_asset stdin environment option'.split(' '),key);if(!unique(p.value_types,key).length)fail(key,'no parameter types');for(const t of p.value_types)if(!values.has(t))fail(key,`unknown type ${t}`);omission(p.omission,key);if(p.omission.kind==='literal'&&!p.value_types.some(t=>typeMatches(p.omission.value,t)))fail(key,'default type mismatch');}
  exact(src.result,['shape','observations','error'],key);enumeration(src.result.shape,'none scalar sequence mapping record bytes image mask encoded_file metrics handle iterator stream cli protocol filesystem'.split(' '),key);for(const a of arr(src.result.observations,key)){exact(a,['path','value_types','comparison'],key);str(a.path,key);unique(a.value_types,key);a.value_types.forEach(t=>{if(!values.has(t))fail(key,'unknown observation type');});comparison(a.comparison,key);}errorContract(src.result.error,key);
  const seen=new Set();for(const b of o.targets){exact(b,['target_id','path','signature','support'],key);ref(b.target_id,r.targets,key);if(seen.has(b.target_id))fail(key,'duplicate binding');seen.add(b.target_id);const support=b.support;const fields={supported:['status'],partial:['status','reason','missing_requirements'],unimplemented:['status','reason','blocker'],intentionally_unsupported:['status','reason','authority'],out_of_scope:['status','reason','authority'],not_applicable:['status','reason']}[support.status];if(!fields)fail(key,'unsupported support status');exact(support,fields,key);for(const k of ['reason','blocker','authority'])if(k in support)str(support[k],key);if(['supported','partial'].includes(support.status)){str(b.path,key);str(b.signature,key);}else if(b.signature!==null)fail(key,'unbound signature must be null');if(support.status==='not_applicable'&&o.classification!=='non_endpoint')fail(key,'endpoint cannot be not applicable');}if(seen.size!==r.targets.size)fail(key,'target binding bijection mismatch');
  if(o.classification==='endpoint'&&!o.requirements.length)fail(key,'endpoint missing semantic requirements');for(const q of o.requirements){exact(q,['id','dimension','description','lanes','target_profiles'],key,['budget']);id(q.id,key);if(r.requirements.has(q.id))fail(key,'duplicate requirement');if(!dimensions.has(q.dimension))fail(key,'unsupported requirement dimension');str(q.description,key);for(const l of unique(q.lanes,key))enumeration(l,['parity','coverage','benchmark'],key);for(const p of unique(q.target_profiles,key))ref(p,r.profiles,key);if(q.budget)budget(q.budget,key,r);r.requirements.set(q.id,{...q,operation:key});}
  for(const lane of ['parity','coverage','benchmark']){const l=o[lane];if(l.applicability==='not_applicable'){exact(l,['applicability','reason'],key);str(l.reason,key);if(o.requirements.some(q=>q.lanes.includes(lane)))fail(key,'non-applicable lane has requirements');continue;}assert.equal(l.applicability,'required');exact(l,['applicability','target_profiles',...(lane==='coverage'?['component_ids']:lane==='benchmark'?['metrics']:[])],key);for(const p of unique(l.target_profiles,key)){ref(p,r.profiles,key);if(!o.requirements.some(q=>q.lanes.includes(lane)&&q.target_profiles.includes(p)))fail(key,'required lane missing profile requirement');}if(lane==='coverage')for(const c of unique(l.component_ids,key))ref(c,r.components,key);if(lane==='benchmark')for(const m of unique(l.metrics,key))if(!metrics.has(m))fail(key,'unknown benchmark metric');}
 }}
 exact(m.documentation,['command_id','specification_outputs','evidence_outputs'],'documentation');ref(m.documentation.command_id,r.commands,'documentation');[...m.documentation.specification_outputs,...m.documentation.evidence_outputs].forEach(p=>safePath(p,'documentation'));return r;
}
export function typeMatches(v,type){switch(type){case'any_json':return v!==undefined;case'null':return v===null;case'boolean':return typeof v==='boolean';case'integer':return Number.isInteger(v);case'number':return typeof v==='number'&&Number.isFinite(v);case'string':case'path':case'enum':return typeof v==='string';case'sequence':return Array.isArray(v);case'mapping':case'record':return v!==null&&typeof v==='object'&&!Array.isArray(v);default:return false;}}
function descriptor(v,p,bindings,assets){str(v?.kind,p);if(v.kind==='literal')exact(v,['kind','value'],p);else if(v.kind==='binding'){exact(v,['kind','step_id'],p);ref(v.step_id,bindings,p);}else if(v.kind==='asset'){exact(v,['kind','asset_id'],p);ref(v.asset_id,assets,p);}else fail(p,'unsupported value descriptor');}
function asset(a,p,registry){const fields={ref:['id','kind','path','sha256','media_type'],inline:['id','kind','encoding','data','sha256','media_type'],generated:['id','kind','path','command_id','seed','sha256','media_type'],builtin:['id','kind','name'],missing:['id','kind','path'],remote_mock:['id','kind','path','command_id','endpoint','sha256','media_type']}[a.kind];if(!fields)fail(p,'unsupported asset');exact(a,fields,p);id(a.id,p);if('path'in a)safePath(a.path,p);if('sha256'in a&&!/^[0-9a-f]{64}$/.test(a.sha256))fail(p,'invalid digest');if('command_id'in a)ref(a.command_id,registry.commands,p);if(a.kind==='inline')enumeration(a.encoding,['base64','utf8'],p);}
function workflow(item,r,p){const assets=keyed(item.assets,p);for(const a of assets.values())asset(a,p,r);const bound=new Map(),steps=new Map();for(const s of item.steps){exact(s,['step_id','surface','operation','receiver','arguments'],p);id(s.step_id,p);if(bound.has(s.step_id))fail(p,'duplicate step');const op=r.operations.get(`${s.surface}.${s.operation}`);if(!op)fail(p,`unknown operation ${s.surface}.${s.operation}`);if(s.receiver!==null)descriptor(s.receiver,p,bound,assets);if(!s.arguments||typeof s.arguments!=='object'||Array.isArray(s.arguments))fail(p,'arguments must be object');const params=new Map(op.source.parameters.map(a=>[a.id,a]));for(const [name,d]of Object.entries(s.arguments)){if(!params.has(name))fail(p,`unknown public parameter ${name}`);descriptor(d,p,bound,assets);if(d.kind==='literal'&&!params.get(name).value_types.some(t=>typeMatches(d.value,t)))fail(p,`argument type mismatch ${name}`);}for(const q of params.values())if(q.omission.kind==='required'&&!(q.id in s.arguments)&&q.style!=='receiver')fail(p,`required parameter missing ${q.id}`);bound.set(s.step_id,s);steps.set(s.step_id,s);}if(!unique(item.observations,p).length)fail(p,'empty observations');for(const id of item.observations)ref(id,steps,p);return steps;}
function covers(item,r,p,lane,profiles){for(const req of unique(item.covers,p)){ref(req,r.requirements,p);const q=r.requirements.get(req);if(!q.lanes.includes(lane))fail(p,'requirement lane mismatch');for(const profile of profiles)if(!q.target_profiles.includes(profile))fail(p,'requirement profile mismatch');}}
export function validateInput(input,lane,r,globalIds=new Set()){
 assert.equal(input.schema,schemas[lane]);exact(input,lane==='parity'?['schema','cases']:lane==='coverage'?['schema','plans']:['schema','workloads','suites'],lane);
 const addId=(value)=>{id(value,lane);if(globalIds.has(value))fail(value,'duplicate executable ID');globalIds.add(value);};
 if(lane==='parity')for(const c of input.cases){exact(c,['case_id','surface','operation','covers','target_profiles','assets','steps','observations'],'case');addId(c.case_id);const key=`${c.surface}.${c.operation}`;if(!c.case_id.startsWith(key+'.'))fail(c.case_id,'case id has wrong operation prefix');ref(key,r.operations,c.case_id);c.target_profiles.forEach(p=>ref(p,r.profiles,c.case_id));covers(c,r,c.case_id,lane,c.target_profiles);const steps=workflow(c,r,c.case_id);const observed=new Set(c.observations.map(id=>{const s=steps.get(id);return `${s.surface}.${s.operation}`;}));if(!observed.has(key))fail(c.case_id,'primary operation is not observed');for(const q of c.covers)if(!observed.has(r.requirements.get(q).operation))fail(c.case_id,'covered operation is not observed');}
 if(lane==='coverage')for(const c of input.plans){exact(c,['plan_id','covers','target_profile','selectors','component_ids','command_id'],'plan');addId(c.plan_id);ref(c.target_profile,r.profiles,c.plan_id);ref(c.command_id,r.commands,c.plan_id);covers(c,r,c.plan_id,lane,[c.target_profile]);exact(c.selectors,['parity_case_ids','command_ids'],c.plan_id);unique(c.selectors.parity_case_ids,c.plan_id);c.selectors.command_ids.forEach(id=>ref(id,r.commands,c.plan_id));if(!c.selectors.parity_case_ids.length&&!c.selectors.command_ids.length)fail(c.plan_id,'empty selectors');c.component_ids.forEach(id=>ref(id,r.components,c.plan_id));for(const requirement of c.covers){const op=r.operations.get(r.requirements.get(requirement).operation);for(const id of c.component_ids)if(!op.coverage.component_ids.includes(id))fail(c.plan_id,`component ${id} outside covered operation`);}}
 if(lane==='benchmark'){for(const w of input.workloads){exact(w,['workload_id','covers','subjects','input','measurement'],'workload');addId(w.workload_id);for(const s of w.subjects){exact(s,['kind','id'],w.workload_id);enumeration(s.kind,['oracle','target_profile'],w.workload_id);ref(s.id,s.kind==='oracle'?r.oracles:r.profiles,w.workload_id);}covers(w,r,w.workload_id,lane,w.subjects.filter(s=>s.kind==='target_profile').map(s=>s.id));const i=w.input;if(i.kind==='parity_case')exact(i,['kind','case_id'],w.workload_id);else if(i.kind==='workflow'){exact(i,['kind','assets','steps','observations'],w.workload_id);workflow(i,r,w.workload_id);}else if(i.kind==='command'){exact(i,['kind','command_id'],w.workload_id);ref(i.command_id,r.commands,w.workload_id);}else if(i.kind==='artifact'){exact(i,['kind','path'],w.workload_id);safePath(i.path,w.workload_id);}else fail(w.workload_id,'unknown workload kind');const m=w.measurement;exact(m,['boundary','step_ids','metrics','warmup_iterations','measurement_iterations','samples','concurrency','cache_state','correctness_gate'],w.workload_id);enumeration(m.boundary,['observed_steps','whole_workflow','process','artifact'],w.workload_id);enumeration(m.cache_state,['cold','warm','mixed'],w.workload_id);enumeration(m.correctness_gate,['parity_pass','source_target_match','successful_execution','not_applicable'],w.workload_id);if(m.correctness_gate==='not_applicable'&&m.boundary!=='artifact')fail(w.workload_id,'behavioral workload lacks correctness gate');for(const key of ['measurement_iterations','samples','concurrency'])positive(m[key],w.workload_id);positive(m.warmup_iterations,w.workload_id,true);unique(m.step_ids,w.workload_id);if(m.boundary==='observed_steps'&&!m.step_ids.length)fail(w.workload_id,'no measured steps');for(const metric of m.metrics)if(!metrics.has(metric))fail(w.workload_id,'unknown metric');}for(const s of input.suites){exact(s,['suite_id','description','members'],'suite');addId(s.suite_id);str(s.description,s.suite_id);for(const m of s.members){exact(m,['workload_id','weight'],s.suite_id);positive(m.weight,s.suite_id);}}}
 return input;
}
export function loadManifest(path){const manifest=JSON.parse(readFileSync(path));return {manifest,registry:validateManifest(manifest)};}
export function loadInputs(path,manifest,registry){const dir=resolve(path,'..');const out={parity:[],coverage:[],benchmark:[]},ids=new Set();for(const lane of Object.keys(out)){const indexed=manifest.input_index[lane];const root=join(dir,'inputs',lane);let discovered=[];function scan(dir){for(const entry of readdirSync(dir,{withFileTypes:true})){if(entry.isDirectory())scan(join(dir,entry.name));else if(entry.name.endsWith('.json'))discovered.push(relative(resolve(path,'..'),join(dir,entry.name)));}}scan(root);assert.deepEqual(discovered.sort(),[...indexed].sort(),`${lane} input index mismatch`);for(const file of indexed)out[lane].push({path:file,input:validateInput(JSON.parse(readFileSync(join(dir,file))),lane,registry,ids)});}const parityCases=new Set(out.parity.flatMap(f=>f.input.cases).map(c=>c.case_id));const workloads=new Set(out.benchmark.flatMap(f=>f.input.workloads).map(w=>w.workload_id));for(const f of out.coverage)for(const p of f.input.plans)for(const id of p.selectors.parity_case_ids)ref(id,parityCases,p.plan_id);for(const f of out.benchmark){for(const w of f.input.workloads)if(w.input.kind==='parity_case')ref(w.input.case_id,parityCases,w.workload_id);for(const s of f.input.suites)for(const m of s.members)ref(m.workload_id,workloads,s.suite_id);}for(const f of out.parity)for(const c of f.input.cases)for(const a of c.assets){if(a.kind==='inline'){const bytes=Buffer.from(a.data,a.encoding==='base64'?'base64':'utf8');assert.equal(createHash('sha256').update(bytes).digest('hex'),a.sha256,`Inline stimulus digest mismatch ${a.id}`);}if(a.kind==='ref'){const bytes=readFileSync(resolve(dir,'assets',a.path));assert.equal(createHash('sha256').update(bytes).digest('hex'),a.sha256,`Stimulus digest mismatch ${a.path}`);}}return out;}
