use crate::{Engine, terrain::WORLD_EDGE, value::*};
use serde_json::{Value, json};
use std::collections::HashMap;

/// Integer region keys avoid allocation during the hundreds of fog checks in a
/// scout search. Reveals invalidate explicitly; restored worlds start fresh.
#[derive(Default)]
pub struct DiscoveryIndex {
    stamp: Option<(u64, u64, usize)>,
    regions: HashMap<(i64, i64), u64>,
}
impl DiscoveryIndex {
    pub(crate) fn clear(&mut self) {
        self.stamp = None;
        self.regions.clear();
    }
    fn known(&mut self, d: &Value, p: Point) -> bool {
        let cell = num(d, "cell");
        if !d.is_object() || cell <= 0. || !p.x.is_finite() || !p.y.is_finite() {
            return false;
        }
        let regions = d["regions"].as_object();
        let stamp = (
            num(d, "revision").to_bits(),
            cell.to_bits(),
            regions.map_or(0, |v| v.len()),
        );
        if self.stamp != Some(stamp) {
            self.regions.clear();
            if let Some(regions) = regions {
                for (key, mask) in regions {
                    let Some((x, y)) = key.split_once(':') else {
                        continue;
                    };
                    let (Ok(x), Ok(y)) = (x.parse::<i64>(), y.parse::<i64>()) else {
                        continue;
                    };
                    // A noncanonical key would never be generated by the old
                    // coordinate lookup and must not reveal a different cell.
                    if format!("{x}:{y}") == *key {
                        self.regions.insert((x, y), uint(mask).unwrap_or(0));
                    }
                }
            }
            self.stamp = Some(stamp);
        }
        let x = (p.x / cell).floor() as i64;
        let y = (p.y / cell).floor() as i64;
        let cx = x.div_euclid(4);
        let cy = y.div_euclid(4);
        let bit = 1 << ((y - cy * 4) * 4 + x - cx * 4);
        self.regions.get(&(cx, cy)).copied().unwrap_or(0) & bit != 0
    }
}
fn cell_key(x: i64, y: i64) -> (String, u64) {
    let cx = x.div_euclid(4);
    let cy = y.div_euclid(4);
    (format!("{cx}:{cy}"), 1 << ((y - cy * 4) * 4 + x - cx * 4))
}
fn mark(d: &mut Value, x: i64, y: i64) -> bool {
    let (key, bit) = cell_key(x, y);
    let before = uint(&d["regions"][&key]).unwrap_or(0);
    d["regions"][key] = json!(before | bit);
    before != before | bit
}
pub fn create() -> Value {
    json!({"version":1,"cell":4,"revision":0,"regions":{}})
}
fn compact(d: &mut Value) {
    while d["regions"].as_object().map_or(0, |r| r.len()) > 2048 {
        let old = d["regions"].take();
        d["regions"] = json!({});
        if let Some(regions) = old.as_object() {
            for (key, mask) in regions {
                let Some((cx, cy)) = key.split_once(':') else {
                    continue;
                };
                let (Ok(cx), Ok(cy)) = (cx.parse::<i64>(), cy.parse::<i64>()) else {
                    continue;
                };
                for bit in 0..16 {
                    if uint(mask).unwrap_or(0) & (1 << bit) != 0 {
                        mark(
                            d,
                            (cx * 4 + bit % 4).div_euclid(2),
                            (cy * 4 + bit / 4).div_euclid(2),
                        );
                    }
                }
            }
        }
        let cell = num(d, "cell") * 2.;
        d["cell"] = json!(cell);
    }
}
pub fn reveal(d: &mut Value, p: Point, radius: f64) -> bool {
    if !d.is_object() || !p.x.is_finite() || !p.y.is_finite() {
        return false;
    }
    let cell = num(d, "cell");
    let p = Point {
        x: p.x.clamp(-WORLD_EDGE, WORLD_EDGE),
        y: p.y.clamp(-WORLD_EDGE, WORLD_EDGE),
    };
    let radius = cell.max(radius.min(64.));
    let mut changed = false;
    for gy in ((p.y - radius) / cell).floor() as i64..=((p.y + radius) / cell).floor() as i64 {
        for gx in ((p.x - radius) / cell).floor() as i64..=((p.x + radius) / cell).floor() as i64 {
            if (Point {
                x: (gx as f64 + 0.5) * cell,
                y: (gy as f64 + 0.5) * cell,
            })
            .distance(p)
                <= radius
            {
                changed = mark(d, gx, gy) || changed;
            }
        }
    }
    if changed {
        compact(d);
        increment(d, "revision", 1.);
    }
    changed
}
#[allow(
    clippy::manual_clamp,
    reason = "Legacy revision migration converts NaN to zero; clamp would preserve NaN."
)]
pub fn normalize(raw: &Value, w: &Value) -> Result<Value, String> {
    let mut d = create();
    if !raw.is_null() {
        let cell = num(raw, "cell");
        if num(raw, "version") != 1.
            || cell.fract() != 0.
            || !(4. ..=4294967296.).contains(&cell)
            || cell.log2().fract() != 0.
            || !raw["regions"].is_object()
            || raw["regions"].as_object().map_or(0, |r| r.len()) > 2048
        {
            return Err(
                "This saved world's explored map is invalid or needs a newer version.".into(),
            );
        }
        d["cell"] = json!(cell);
        if let Some(regions) = raw["regions"].as_object() {
            for (key, mask) in regions {
                let parts: Vec<_> = key.split(':').collect();
                let valid = parts.len() == 2
                    && parts
                        .iter()
                        .all(|p| region_key_part(p, 10, WORLD_EDGE / (cell * 4.) + 1.));
                if !valid || !uint(mask).is_some_and(|m| (1..=65535).contains(&m)) {
                    return Err("This saved world's explored map is damaged.".into());
                }
                d["regions"][key] = mask.clone();
            }
        }
        d["revision"] = json!(js_number(&raw["revision"]).max(0.).min(1e12));
        return Ok(d);
    }
    reveal(&mut d, Point { x: 32., y: 24. }, 40.);
    for o in list(w, "objects").iter().filter(|o| {
        !["tree", "rock", "flowers", "stump", "node", "mountain"].contains(&text(o, "type"))
    }) {
        reveal(&mut d, Point::read(o), 10.);
    }
    for c in list(w, "creatures") {
        reveal(&mut d, Point::read(c), 10.);
    }
    for v in list(&w["community"], "visited") {
        if let Some((x, y)) = v.as_str().unwrap_or("").split_once(':')
            && let (Ok(x), Ok(y)) = (x.parse::<f64>(), y.parse::<f64>())
        {
            reveal(
                &mut d,
                Point {
                    x: x * 8. + 4.,
                    y: y * 8. + 4.,
                },
                10.,
            );
        }
    }
    Ok(d)
}
impl Engine {
    pub(crate) fn reveal(&mut self, p: Point, radius: f64) -> bool {
        let changed = reveal(&mut self.world["discovery"], p, radius);
        if changed {
            self.discovery_index.borrow_mut().clear();
        }
        changed
    }
    pub(crate) fn reveal_colony(&mut self) {
        let points: Vec<_> = list(&self.world, "creatures")
            .iter()
            .map(Point::read)
            .collect();
        for p in points {
            self.reveal(p, 10.);
        }
    }
    pub(crate) fn is_explored(&self, p: Point) -> bool {
        if num(&self.world, "stage") >= 3. {
            return true;
        }
        self.discovery_index
            .borrow_mut()
            .known(&self.world["discovery"], p)
    }
    pub(crate) fn discovery_summary(&self) -> Value {
        let d = &self.world["discovery"];
        let cells = d["regions"].as_object().map_or(0, |r| {
            r.values()
                .map(|m| uint(m).unwrap_or(0).count_ones())
                .sum::<u32>()
        });
        let cell = num(d, "cell");
        json!({"area":f64::from(cells)*cell*cell,"resolution":cell,"regions":d["regions"].as_object().map_or(0,|r|r.len())})
    }
}
